sudo: required
language: python
python:
  - "3.5"
services:
  - docker
install:
  - docker pull jfloff/alpine-python:latest-slim
  - docker build -t fun-bot .
  - docker run -td fun-bot python3 run.py --dev
script:
  - docker ps | grep fun-bot
